languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
enableEmoji = true

theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://1x-eng.github.io/cv"
title = "Pruthvi - CV"
googleAnalytics = "G-V509B30S01"

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#428bca"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#428bca"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#428bca"
pages = 1
# Set this param to 'true' to swap the bar positions
swapColumns = false
